// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSQLGFf4KzGGI64C6FPe1tka3kFUTCxQ',
    appId: '1:339454277073:web:60b48789d6add6933f5cf0',
    messagingSenderId: '339454277073',
    projectId: 'the-real-me-82bd9',
    authDomain: 'the-real-me-82bd9.firebaseapp.com',
    storageBucket: 'the-real-me-82bd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vVt_ZWvdVeVTZTIgaXBq4Z9MedaHJps',
    appId: '1:339454277073:android:1c9d289c47ee0ca03f5cf0',
    messagingSenderId: '339454277073',
    projectId: 'the-real-me-82bd9',
    storageBucket: 'the-real-me-82bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKX_fyoOVVpczxuuic_hswivdPjWShcKw',
    appId: '1:339454277073:ios:3ab6e6d628f831ca3f5cf0',
    messagingSenderId: '339454277073',
    projectId: 'the-real-me-82bd9',
    storageBucket: 'the-real-me-82bd9.appspot.com',
    iosClientId: '339454277073-5k5raepprgmd7e5j60shm2lll1ntvr9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.radarChartsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKX_fyoOVVpczxuuic_hswivdPjWShcKw',
    appId: '1:339454277073:ios:3ab6e6d628f831ca3f5cf0',
    messagingSenderId: '339454277073',
    projectId: 'the-real-me-82bd9',
    storageBucket: 'the-real-me-82bd9.appspot.com',
    iosClientId: '339454277073-5k5raepprgmd7e5j60shm2lll1ntvr9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.radarChartsApp',
  );
}
